export const WORDS = [
  ['~을 존중하다', 'respect'],
  ['의지', 'will'],
  ['개인, 개인의', 'individual'],
  ['편하게 생각해', 'Take it easy'],
  ['~(관계 등)을 유지하다', 'maintain'],
  ['시각, 태도', 'outlook'],
  ['공평한', 'fair'],
  ['~에 관계없이', 'regardless of'],
  ['신조', 'creed'],
  ['헌법', 'constitution'],
  ['몸을 기울이다', 'lean'],
  ['기둥', 'pillar'],
  ['물끄러미 바라보다', 'gaze'],
  ['조각상', 'statue'],
  ['~의 옆을 지나가다', 'pass by'],
  ['~(냄새, 빛, 열)을 발산하다', 'give off'],
  ['희미한', 'subtle'],
  ['냄새, 향기', 'scent'],
  ['향수', 'perfume'],
  ['~(사람)에게 생각나게 하다.', 'remind'],
  ['심한', 'awful'],
  ['~한 맛이 나다', 'taste'],
  ['훌륭한', 'terrific'],
  ['흠뻑 젖은', 'soaked'],
  ['땀', 'sweat'],
  ['뒤로 물러서다', 'stand back'],
  ['악취가 나다', 'stink'],
  ['샤워를 하다', 'take a shower'],
  ['거의 ~하지 않다', 'scarcely'],
  ['A와 B를 구별하다', 'tell A from B'],
  ['산문', 'prose'],
  ['시', 'poetry'],
  ['최신의', 'up-to-date'],
  ['백과 사전', 'encyclopedia'],
  ['나오다, 발매 되다', 'come out'],
];